### ISSUE TITLE
Error: null value in column "Id" violates not-null constraint.

### ISSUE THREAD

**Issue by Vasto** [neisbut/Npgsql.Bulk#14]
Hello I'm getting an error: "null value in column "Id" violates not-null constraint." when I try to bulk insert instances of following entity:

```    
public class SomeClass
{
        public Guid Id { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public Guid SomeRefId { get; set; }
        public Guid SomeOtherRefId { get; set; }
        public Guid ReportId { get; set; }
        public Guid? AssignationAuthorId { get; set; }
        public DateTime? AssignationDateTime { get; set; }
        public double? SomeValue { get; set; }
        public bool SomeBoolValue { get; set; }
}
```
Here is how the exception looks like

```
{Npgsql.PostgresException (0x80004005): 23502: null value in column "Id" violates not-null constraint
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.<NextResult>d__46.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 467
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult() in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 340
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__100.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1231
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1130
   at Npgsql.Bulk.NpgsqlBulkUploader.Insert[T](IEnumerable`1 entities, InsertConflictAction onConflict)
   at Core.Infrastructure.Storage.EntityFramework.DbContextBulkOperationsExtensions.BulkInsert[T](DbContext context, IList`1 entities) in .... line 16}```
```
Exception details:
```Failing row contains (null, 2019-03-27 11:16:32.534, null, d1292198-df7c-4d6d-a08b-822d0206c5e6, 000006ac-81b8-47dd-b243-0a9e36b961ef, dfdb2783-996c-47c9-b086-7608c7e3c2b1, 0e00cd16-f163-4645-88fe-7c2977f0355b, 2019-01-04 10:28:21, 15.0358169334254, t)."```

Id type in my datatabase is uuid

EDIT:

I think the problem happens when data are copied from temporary table to destination table. I don't see id in Insert command and query which selects from temporary table. Does it assuemes that id is autogenerated and ommits it? If so can I somehow force copying of id?

**Comment by pacoferre** [comment]
Hello @Vasto, perhaps I can help :)

The id is not autogenerated if you don't ask.

You can get autogenerated uuid in two ways; generated on postgre, or in your "client" .NET code.

On postgre, they explain how in this URL https://www.npgsql.org/efcore/value-generation.html.

![image](https://user-images.githubusercontent.com/10376690/55088105-712e4c00-50ab-11e9-890c-c2ca2ed3d5c4.png)

On your "client" code is a little bit tricky. but you can get more control over generation process.

The uuid must be decorated with attributes:

        [Key, DatabaseGenerated(DatabaseGeneratedOption.None)]
        public Guid TheId { get; set; }

Then, in DbContext OnModelCreating override

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

You must set a Value generator

                    modelBuilder
                        .Entity("Entity")
                        .Property(_ => _.TheId)
                        .HasValueGenerator<GuidValueGenerator>()
                        .ValueGeneratedOnAdd();

And finally, create the GuidValueGenerator.

    public class GuidValueGenerator : ValueGenerator<Guid>
    {
        public GuidValueGenerator()
        {
        }

        public override bool GeneratesTemporaryValues => false;

        public override Guid Next(EntityEntry entry)
        {
            if (entry == null)
            {
                throw new ArgumentNullException(nameof(entry));
            }

            return SequentialGuid.Create();
        }
    }

SequencialGuid class was taken from https://www.codeproject.com/Articles/388157/GUIDs-as-fast-primary-keys-under-multiple-database.

And I set by default the recommended postgree uuid generator type.

        public static Guid Create(SequentialGuidType guidType = SequentialGuidType.SequentialAsString) // Postgre

**Comment by Vasto** [comment]
@pacoferre Thank you! 

Setting ValueGeneratedOnAdd or [Key, DatabaseGenerated(DatabaseGeneratedOption.None)] attribute solves my issue.
