### ISSUE TITLE
EF Core 3.1: Error when trying to bulk upload entities with xmin concurrency token

### ISSUE THREAD

**Issue by msvprogs** [neisbut/Npgsql.Bulk#44]
Suppose I have the following entity:
```csharp
public class BrandConfiguration : IEntityTypeConfiguration<Brand>
{
   public void Configure(EntityTypeBuilder<Brand> builder)
   {
      builder.UseXminAsConcurrencyToken()
         .HasKey(x => x.Id);
   }
}
```

Then the following code will fail:
```csharp
var loader = new NpgsqlBulkUploader(_context);

return loader.InsertAsync(
	new[] { new Brand { Id = 1, Name = "test" } },
	InsertConflictAction.DoNothing()
);
```

Error:
```
System.InvalidOperationException : Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Npgsql.Bulk.NpgsqlHelper.<>c__DisplayClass1_0.<GetMetadata>b__1(IProperty x)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Npgsql.Bulk.NpgsqlHelper.GetMetadata(DbContext context, Type type)
   at Npgsql.Bulk.NpgsqlBulkUploader.GetMappingInfo(Type type, String tableName)
   at Npgsql.Bulk.NpgsqlBulkUploader.CreateEntityInfo[T]()
   at Npgsql.Bulk.NpgsqlBulkUploader.<GetEntityInfo>b__44_0[T](Type x)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Npgsql.Bulk.NpgsqlBulkUploader.GetEntityInfo[T]()
   at Npgsql.Bulk.NpgsqlBulkUploader.InsertAsync[T](IEnumerable`1 entities, InsertConflictAction onConflict)
   at xxxx.Updating() in D:\xxxx.cs:line 283
```

I've found that this is caused by 'xmin' internal column, which isn't returned when querying table schema from DB, but is included in EF property list.

Note: this error appears *only on EF Core 3.1*. It was working properly when used with EF Core 2.2.

PostgreSQL version: 10.11

**Comment by neisbut** [comment]
Hi @msvprogs, sorry for such a late answer.. I fixed this in 0.8.1, please check when possible.

**Comment by msvprogs** [comment]
Ok, thanks, but there's also a bug in the IL generator: https://github.com/msvprogs/Npgsql.Bulk/commit/dcc8e6f7a0172c9700a8d88abdedbc486dbc2eef#diff-89769ade052cc1dede7567bc2397de09

**Comment by neisbut** [comment]
Oh, thanks! I added it in 0.8.1.1

**Comment by msvprogs** [comment]
Thanks for quick answer!
