### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by smartpcr** [neisbut/Npgsql.Bulk#49]
when I call the following method
``` cs
        public async Task<int> Ingest(IEnumerable<T> source, CancellationToken cancel)
        {
            var list = source.GroupBy(r => r.GetKeyValue()).Select(g => g.First()).ToList();
            var count = list.Count;

            if (list.Count > 0)
            {
                logger.LogInformation($"adding {typeof(T).Name}...");
                var stopwatch = Stopwatch.StartNew();

                var uploader = new NpgsqlBulkUploader(dbContext);
                await uploader.InsertAsync(list);
                logger.LogInformation($"it took {stopwatch.Elapsed} to injest {count} records");
            }

            return count;
        }
```

error occurred on line with code `await uploader.InsertAsync(list);`:
``` log
[20:45:43 INF] adding ElectricalDeviceForEquipment...
[20:48:08 INF] Executed DbCommand (227ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
CREATE TEMP TABLE _temp__35c46611_47c6_4ba6_80f6_4fb0596b9115_2 ON COMMIT DROP AS SELECT "ElectricalDevicesForEquipment"."Id" AS electricaldevicesforequipment_id, "ElectricalDevicesForEquipment"."ArgusRuleTemplate" AS electricaldevicesforequipment_argusruletemplat
e, "ElectricalDevicesForEquipment"."ChannelDescription" AS electricaldevicesforequipment_channeldescription, "ElectricalDevicesForEquipment"."ChannelTypeName" AS electricaldevicesforequipment_channeltypename, "ElectricalDevicesForEquipment"."CreatedBy" AS electric
aldevicesforequipment_createdby, "ElectricalDevicesForEquipment"."CreationTime" AS electricaldevicesforequipment_creationtime, "ElectricalDevicesForEquipment"."DataPoint" AS electricaldevicesforequipment_datapoint, "ElectricalDevicesForEquipment"."DataPointTag" AS
 electricaldevicesforequipment_datapointtag, "ElectricalDevicesForEquipment"."DcCode" AS electricaldevicesforequipment_dccode, "ElectricalDevicesForEquipment"."DcName" AS electricaldevicesforequipment_dcname, "ElectricalDevicesForEquipment"."DeviceFamily" AS elect
ricaldevicesforequipment_devicefamily, "ElectricalDevicesForEquipment"."DeviceName" AS electricaldevicesforequipment_devicename, "ElectricalDevicesForEquipment"."DevicePath" AS electricaldevicesforequipment_devicepath, "ElectricalDevicesForEquipment"."DeviceState"
 AS electricaldevicesforequipment_devicestate, "ElectricalDevicesForEquipment"."DeviceTags" AS electricaldevicesforequipment_devicetags, "ElectricalDevicesForEquipment"."DeviceType" AS electricaldevicesforequipment_devicetype, "ElectricalDevicesForEquipment"."Hier
archy" AS electricaldevicesforequipment_hierarchy, "ElectricalDevicesForEquipment"."HierarchyId" AS electricaldevicesforequipment_hierarchyid, "ElectricalDevicesForEquipment"."LowerDeadBand" AS electricaldevicesforequipment_lowerdeadband, "ElectricalDevicesForEqui
pment"."ModificationTime" AS electricaldevicesforequipment_modificationtime, "ElectricalDevicesForEquipment"."ModifiedBy" AS electricaldevicesforequipment_modifiedby, "ElectricalDevicesForEquipment"."PanelName" AS electricaldevicesforequipment_panelname, "Electric
alDevicesForEquipment"."PrimaryParents" AS electricaldevicesforequipment_primaryparents, "ElectricalDevicesForEquipment"."QueryPanel" AS electricaldevicesforequipment_querypanel, "ElectricalDevicesForEquipment"."Rating" AS electricaldevicesforequipment_rating, "El
ectricalDevicesForEquipment"."Reason" AS electricaldevicesforequipment_reason, "ElectricalDevicesForEquipment"."RedundantDeviceInformation" AS electricaldevicesforequipment_redundantdeviceinformation, "ElectricalDevicesForEquipment"."RedundantDeviceNames" AS elect
ricaldevicesforequipment_redundantdevicenames, "ElectricalDevicesForEquipment"."RuleId" AS electricaldevicesforequipment_ruleid, "ElectricalDevicesForEquipment"."Source" AS electricaldevicesforequipment_source, "ElectricalDevicesForEquipment"."TS" AS electricaldev
icesforequipment_ts, "ElectricalDevicesForEquipment"."UpperDeadBand" AS electricaldevicesforequipment_upperdeadband, "ElectricalDevicesForEquipment"."Validate" AS electricaldevicesforequipment_validate FROM "ElectricalDevicesForEquipment" LIMIT 0
[20:48:15 INF] Executed DbCommand (37ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE _temp__35c46611_47c6_4ba6_80f6_4fb0596b9115_2 ADD COLUMN __index integer
[20:48:24 ERR] Failed sync: Arithmetic operation resulted in an overflow.
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Npgsql.TypeHandlers.NumericHandlers.Int32Handler.Write(Double value, NpgsqlWriteBuffer buf, NpgsqlParameter parameter)
   at Npgsql.TypeHandling.NpgsqlSimpleTypeHandler`1.WriteWithLengthInternal[TAny](TAny value, NpgsqlWriteBuffer buf, NpgsqlLengthCache lengthCache, NpgsqlParameter parameter, Boolean async)
   at Npgsql.NpgsqlParameter`1.WriteWithLength(NpgsqlWriteBuffer buf, Boolean async)
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlParameter param, Boolean async)
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlDbType npgsqlDbType)
   at ElectricalDeviceForEquipment_198bd14d_36be_4bb4_9672_8f754439f90d_1.WriterForInsertAction(ElectricalDeviceForEquipment , NpgsqlBinaryImporter , DbContext )
   at Npgsql.Bulk.NpgsqlBulkUploader.WriteInsertPortion[T](IEnumerable`1 list, EntityInfo mapping, NpgsqlConnection conn, String tempTableName, NpgsqlBulkCodeBuilder`1 codeBuilder)
   at Npgsql.Bulk.NpgsqlBulkUploader.InsertAsync[T](IEnumerable`1 entities, InsertConflictAction onConflict)
   at DataCenterHealth.Repositories.EntityRepo`1.Ingest(IEnumerable`1 source, IngestMode ingestMode, CancellationToken cancel) in E:\work\my\dq\src\DataQuality\src\Models\DataCenterHealth.Repositories\EntityRepo.cs:line 269

```

**Comment by smartpcr** [comment]
exception from
