### ISSUE TITLE
Update Npgsql.EntityFrameworkCore.PostgreSQL

### ISSUE THREAD

**Issue by GeorgyRezchikov** [neisbut/Npgsql.Bulk#55]
Please update the version of the Npgsql.EntityFrameworkCore.PostgreSQL package to the stable version 5.0.0

**Comment by ptrushin** [comment]
+1
I got an exception when update ef and pg lib to 5.0.0
An unhandled exception has occurred while executing the request.
System.MissingMethodException: Method not found: 'Npgsql.NpgsqlDataReader Npgsql.NpgsqlCommand.ExecuteReader()'.
   at Npgsql.Bulk.RelationalHelper.GetColumnsInfo(DbContext context, String tableName)
   at Npgsql.Bulk.NpgsqlHelper.GetMetadata(DbContext context, Type type)
   at Npgsql.Bulk.NpgsqlBulkUploader.GetMappingInfo(Type type, String tableName)
   at Npgsql.Bulk.NpgsqlBulkUploader.CreateEntityInfo[T]()
   at Npgsql.Bulk.NpgsqlBulkUploader.<GetEntityInfo>b__50_0[T](String x)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Npgsql.Bulk.NpgsqlBulkUploader.GetEntityInfo[T]()
   at Npgsql.Bulk.NpgsqlBulkUploader.Insert[T](IEnumerable`1 entities, InsertConflictAction onConflict)
   at Npgsql.Bulk.NpgsqlBulkUploader.Insert[T](IEnumerable`1 entities)

**Comment by neisbut** [comment]
Hi @GeorgyRezchikov, .Net 5 should be supported now in 0.9.0 release. Please check, thanks!

**Comment by GeorgyRezchikov** [comment]
Thank you, it works.
