### ISSUE TITLE
i am a problem with data type of Nullable<DateTime>

### ISSUE THREAD

**Issue by kenan19** [neisbut/Npgsql.Bulk#6]
hello,
for example, my entity contains a column with nullable datetime
but when i use this sdk, it throw an exception,can you relove or fix it? thank you 

Unhandled Exception: System.InvalidCastException: Can't write CLR type System.Nullable`1[System.DateTime] to database type timestamp
   at Npgsql.TypeHandling.NpgsqlSimpleTypeHandler`1.ValidateAndGetLength[TAny](TAny value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter) in C:\Users\kenan19\Downloads\npgsql-dev\src\Npgsql\TypeHandling\NpgsqlSimpleTypeHandler.cs:line 171
   at Npgsql.NpgsqlParameter`1.ValidateAndGetLength() in C:\Users\kenan19\Downloads\npgsql-dev\src\Npgsql\NpgsqlParameter`.cs:line 96
   at Npgsql.NpgsqlBinaryImporter.Write[T](T value, NpgsqlParameter param) in C:\Users\kenan19\Downloads\npgsql-dev\src\Npgsql\NpgsqlBinaryImporter.cs:line 244

**Comment by neisbut** [comment]
Hi @kenan19 , sorry for a late answer. There was a breaking change in Npgsql package (which is used by Npgsql.Bulk) which caused this issue. I fixed this issue in latest release 0.6.0. Please check.
